In [1]:
import pandas as pd

data = pd.DataFrame(columns=['dim1', 'dim2', 'dim3', 'value'])

for i in range(5):
    for j in range(4):
        for k in range(3):
            value = i * j * k
            data.loc[len(data)] = [i, j, k, value]

data

    dim1  dim2  dim3  value
0      0     0     0      0
1      0     0     1      0
2      0     0     2      0
3      0     1     0      0
4      0     1     1      0
5      0     1     2      0
6      0     2     0      0
7      0     2     1      0
8      0     2     2      0
9      0     3     0      0
10     0     3     1      0
11     0     3     2      0
12     1     0     0      0
13     1     0     1      0
14     1     0     2      0
15     1     1     0      0
16     1     1     1      1
17     1     1     2      2
18     1     2     0      0
19     1     2     1      2
20     1     2     2      4
21     1     3     0      0
22     1     3     1      3
23     1     3     2      6
24     2     0     0      0
25     2     0     1      0
26     2     0     2      0
27     2     1     0      0
28     2     1     1      2
29     2     1     2      4
30     2     2     0      0
31     2     2     1      4
32     2     2     2      8
33     2     3     0      0
34     2     3     1      6
35     2     3     2     12
36     3     0     0      0
37     3     0     1      0
38     3     0     2      0
39     3     1     0      0
40     3     1     1      3
41     3     1     2      6
42     3     2     0      0
43     3     2     1      6
44     3     2     2     12
45     3     3     0      0
46     3     3     1      9
47     3     3     2     18
48     4     0     0      0
49     4     0     1      0
50     4     0     2      0
51     4     1     0      0
52     4     1     1      4
53     4     1     2      8
54     4     2     0      0
55     4     2     1      8
56     4     2     2     16
57     4     3     0      0
58     4     3     1     12
59     4     3     2     24